apiVersion: v1
kind: ConfigMap
metadata:
  name: eve-registry-config
  namespace: eve-system
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: eve-registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
