#!/usr/bin/env bash
# forbid-fake-recipients.sh
#
# Repo-hygiene lint: forbid throwaway / pollution-prone recipient patterns in
# manual test scenarios.
#
# Background
# ----------
# Agent-driven smoke tests (e.g. magic-link login, app invites) have historically
# generated recipients like `user+app-smoke-1778413063@example.com` and
# `cli-invite-1770924851@example.com`. When these hit SES, account-level
# suppression entries pile up against a production domain and silently drop
# future real mail to real users (see docs/plans/magic-link-email-silent-drop-plan.md).
#
# This lint refuses to let those patterns into committed scenario files. For
# anything that needs to exercise the real mailer path, use SES's mailbox
# simulator instead:
#
#   success@simulator.amazonses.com           # always delivers
#   bounce@simulator.amazonses.com            # always bounces (no suppression)
#   suppressionlist@simulator.amazonses.com   # simulated suppressed-recipient bounce
#
# AWS reference:
#   https://docs.aws.amazon.com/ses/latest/dg/send-an-email-using-the-mailbox-simulator.html
#
# Mailpit-only scenarios (local k3d) can keep using `@eve.local` recipients —
# Mailpit captures every outbound message, no real network egress, no SES.
#
# Usage:
#   tests/scenario-lint/forbid-fake-recipients.sh             # lint all scenarios
#   tests/scenario-lint/forbid-fake-recipients.sh path/to.md  # lint specific files
#
# Exit codes:
#   0  clean
#   1  one or more forbidden patterns found
#   2  invocation / environment error
#
# Portability: BSD-grep compatible (works on macOS default grep and GNU grep).
# Uses only POSIX shell features plus `grep -E -n -H` and `find`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCENARIOS_DIR="$REPO_ROOT/tests/manual/scenarios"

# Real @example.com mailboxes that are allowed to appear in scenarios.
# These are humans who actually read their mail; they will not be filled with
# plus-tag throwaways. Extend deliberately (PR review) — every new entry is a
# new bounce-risk vector.
ALLOWED_PRODUCTION_ADDRESSES=(
  "admin@example.com"
  "dan@example.com"
  "pierre.davies@example.com"
)

# Forbidden substring patterns. Each is a `grep -E` regex evaluated against the
# raw scenario file. A line matching ANY pattern is reported. Patterns are kept
# narrow enough that allowed addresses above do not match them.
#
# Rationale per pattern:
#   - `+smoke`        : agent smoke-run plus-tags (e.g. adam+acme-smoke-...)
#   - `+test`         : generic plus-tag test aliases (e.g. user+test123@...)
#   - `+qa_`          : QA plus-tags (e.g. iain.partner+qa_partner@example.com)
#   - `+prod_`        : prod-test plus-tags (e.g. hilary+prod_testpartner@...)
#   - `+partner`      : partner plus-tags (e.g. ssasha+partner0414@example.com)
#   - `cli-invite-`   : autogenerated CLI invite recipients into @example.com
#   - `invite-test-`  : autogenerated invite-test recipients into @example.com
#   - `smoke-[0-9]`   : smoke timestamps (e.g. acme-smoke-1778413063)
#   - `-test@example` : suffix-style test mailboxes (e.g. simone.porter-test@...)
#
# The `@example\.com` boundary is enforced so we don't false-positive on local
# `@eve.local`, simulator, or `@reference-app.eve` recipients.
FORBIDDEN_PRODUCTION_PATTERNS=(
  '\+smoke[^@[:space:]]*@example\.com'
  '\+test[^@[:space:]]*@example\.com'
  '\+qa_[^@[:space:]]*@example\.com'
  '\+prod_[^@[:space:]]*@example\.com'
  '\+partner[^@[:space:]]*@example\.com'
  'cli-invite-[^@[:space:]]*@example\.com'
  'invite-test-[^@[:space:]]*@example\.com'
  '[a-zA-Z0-9._-]+-smoke-[0-9]+[^@[:space:]]*@example\.com'
  '[a-zA-Z0-9._+-]+-test@example\.com'
)

# TODO(lint): we don't yet sniff fake recipients in *other* production domains.
# If we start sending to e.g. acme.example in scenarios, extend this list
# rather than working around it in scenario code.

color() {
  # color CODE TEXT — emits ANSI if stdout is a TTY, otherwise plain text.
  local code="$1"; shift
  if [[ -t 1 ]]; then
    printf '\033[%sm%s\033[0m' "$code" "$*"
  else
    printf '%s' "$*"
  fi
}

print_simulator_hint() {
  echo
  echo "Use SES mailbox simulator addresses for any scenario that exercises the"
  echo "real SES delivery path:"
  echo "  - success@simulator.amazonses.com           (always delivers)"
  echo "  - bounce@simulator.amazonses.com            (always bounces; no suppression)"
  echo "  - suppressionlist@simulator.amazonses.com   (simulated suppressed-recipient bounce)"
  echo "AWS docs: https://docs.aws.amazon.com/ses/latest/dg/send-an-email-using-the-mailbox-simulator.html"
  echo
  echo "Mailpit scenarios should keep using @eve.local recipients (local-only,"
  echo "no SES, no bounce risk)."
}

# Determine the file list. If args are passed, use them; otherwise walk the
# scenarios directory (recursive, *.md only).
declare -a TARGET_FILES=()
if [[ $# -gt 0 ]]; then
  TARGET_FILES=("$@")
else
  if [[ ! -d "$SCENARIOS_DIR" ]]; then
    echo "lint: scenarios directory not found at $SCENARIOS_DIR" >&2
    exit 2
  fi
  # shellcheck disable=SC2207 # newline-safe: scenario names have no newlines
  TARGET_FILES=($(find "$SCENARIOS_DIR" -type f -name '*.md' | sort))
fi

if [[ ${#TARGET_FILES[@]} -eq 0 ]]; then
  echo "lint: no scenario files to check"
  exit 0
fi

# Build a single combined ERE so we only walk each file once.
COMBINED_PATTERN=""
for pat in "${FORBIDDEN_PRODUCTION_PATTERNS[@]}"; do
  if [[ -z "$COMBINED_PATTERN" ]]; then
    COMBINED_PATTERN="$pat"
  else
    COMBINED_PATTERN="$COMBINED_PATTERN|$pat"
  fi
done

# Build an allowlist regex used to *post-filter* matches. We match anything that
# is exactly one of the allowed addresses on a word boundary. If a forbidden
# pattern matched but the actual address on that line is in the allowlist, we
# treat the line as clean. In practice the forbidden patterns above don't match
# the bare allowed addresses (none contain `+smoke`/`+test`/etc.), but this
# keeps the lint robust if someone writes `admin@example.com, foo+test@...` on
# one line — we still want to fail on that line because of the second address.
declare -a ALLOWED_REGEXES=()
for addr in "${ALLOWED_PRODUCTION_ADDRESSES[@]}"; do
  # escape regex metacharacters in literal address (only `.` is relevant here)
  ALLOWED_REGEXES+=("${addr//./\\.}")
done

FAIL=0
declare -a FAILING_FILES=()

for f in "${TARGET_FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "lint: skipping non-file argument: $f" >&2
    continue
  fi

  # grep -E -n -H: ERE, line numbers, with filename. -I to skip binary just in case.
  # We don't use -o because we want to show the full offending line for context.
  if matches=$(grep -E -n -H -I "$COMBINED_PATTERN" "$f" 2>/dev/null); then
    # Filter out lines that *only* match because of an allowed address (very rare;
    # we keep the noise low by checking whether the captured forbidden substring
    # itself equals an allowed address — it never will, but be explicit).
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      if [[ $FAIL -eq 0 ]]; then
        color '1;31' "FAIL: forbidden recipient pattern(s) found"; echo
        echo "(See $SCRIPT_DIR/$(basename "$0") for the full pattern list.)"
        echo
      fi
      FAIL=1
      printf '  %s\n' "$line"
    done <<< "$matches"
    FAILING_FILES+=("$f")
  fi
done

if [[ $FAIL -ne 0 ]]; then
  echo
  echo "Failing files:"
  # de-dup
  printf '  - %s\n' "${FAILING_FILES[@]}" | sort -u
  print_simulator_hint
  exit 1
fi

color '0;32' "OK"; echo ": no fake recipient patterns in ${#TARGET_FILES[@]} scenario file(s)."
exit 0
