#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=scripts/release/common.sh
source "$(dirname "$0")/common.sh"

[[ $# -eq 5 ]] || release_die 'usage: image.sh build|load|publish kind name version artifact-dir'
action=$1 kind=$2 name=$3 version=$4 directory=$5
ref=$(release_ref "$kind" "$name" "$version")
mkdir -p "$directory"
receipt="$directory/receipt.txt"
archive="$directory/image.tar.gz"

case "$action" in
  build)
    release_native
    [[ -n ${GITHUB_SHA:-} && ${GITHUB_SHA} =~ ^[0-9a-f]{40}$ ]] || release_die 'missing full source SHA'
    if [[ $kind == service ]]; then
      context=.
      dockerfile="apps/$name/Dockerfile"
      target=production
      [[ $name == worker ]] && target=base
    else
      context="docker/toolchains/$name"
      dockerfile="$context/Dockerfile"
      target=
    fi
    args=(buildx build --platform linux/amd64 --provenance=false --sbom=false --load -f "$dockerfile" -t "$ref"
      --label "org.opencontainers.image.source=$source_url"
      --label "org.opencontainers.image.revision=$GITHUB_SHA"
      --label "org.opencontainers.image.version=$version")
    [[ -z $target ]] || args+=(--target "$target")
    if [[ $kind == service ]]; then
      args+=(--build-arg "EVE_BUILD_VERSION=$version" --build-arg "EVE_BUILD_SHA=$GITHUB_SHA"
        --build-arg "EVE_BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)")
    fi
    docker "${args[@]}" "$context"
    release_image_platform "$ref"
    id=$(release_image_id "$ref")
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.source"}}' "$ref") == "$source_url" ]]
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' "$ref") == "$GITHUB_SHA" ]]
    docker save "$ref" | gzip -1 > "$archive"
    hash=$(sha256sum "$archive" | awk '{print $1}')
    printf 'ref=%s\nid=%s\nsha256=%s\nrevision=%s\n' "$ref" "$id" "$hash" "$GITHUB_SHA" > "$receipt"
    echo "frozen $ref id=$id archive_sha256=$hash"
    ;;
  load|publish)
    [[ -s $archive && -s $receipt ]] || release_die "missing frozen artifact for $ref"
    # Receipts are generated by our own build job; validate each field exactly.
    [[ $(sed -n 's/^ref=//p' "$receipt") == "$ref" ]] || release_die 'receipt reference mismatch'
    expected_id=$(sed -n 's/^id=//p' "$receipt")
    expected_hash=$(sed -n 's/^sha256=//p' "$receipt")
    revision=$(sed -n 's/^revision=//p' "$receipt")
    [[ $expected_id =~ ^sha256:[0-9a-f]{64}$ && $expected_hash =~ ^[0-9a-f]{64}$ && $revision =~ ^[0-9a-f]{40}$ ]] || release_die 'invalid receipt fields'
    [[ ${GITHUB_SHA:-} == "$revision" ]] || release_die 'source revision mismatch'
    echo "$expected_hash  $archive" | sha256sum -c -
    docker load -i "$archive"
    [[ $(release_image_id "$ref") == "$expected_id" ]] || release_die 'loaded image identity mismatch'
    release_image_platform "$ref"
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.source"}}' "$ref") == "$source_url" ]] || release_die 'source label mismatch'
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' "$ref") == "$revision" ]] || release_die 'revision label mismatch'
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.version"}}' "$ref") == "$version" ]] || release_die 'version label mismatch'
    if [[ $action == publish ]]; then
      release_native
      release_check_tag_absent "$ref"
      output=$(docker push "$ref")
      echo "$output"
      registry_config=$(docker buildx imagetools inspect --raw "$ref" | jq -er '.config.digest')
      [[ $registry_config == "$expected_id" ]] || release_die "published config differs from qualified artifact: $registry_config != $expected_id"
      echo "published $ref config=$registry_config"
    fi
    ;;
  *) release_die "unknown action $action" ;;
esac
